PREFIX  dct:  <http://purl.org/dc/terms/>
PREFIX  urn:  <http://www.d-nb.de/standards/urn/>
PREFIX  frbr: <http://purl.org/vocab/frbr/core#>
PREFIX  pica: <http://www.ub.uni-marburg.de/webcat/card/ppn/>

## resource dump.
construct {
    <subject> ?p ?o .
    ?x ?y ?z . 
    ?a ?b ?c .
} where {
  {
     <subject> ?p ?o .
     ?s ?p ?o .
     optional {
         ?o ?y ?z .
         ?x ?y ?z .
         optional {
             ?z ?b ?c .
             ?a ?b ?c .
         }
     }
  } 
}

