
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX pica: <http://www.ub.uni-marburg.de/webcat/card/ppn/>

# general resource enumeration : every subject, but no blank nodes
# and newer than date.
# select distinct ?subject 
# select distinct ?Concept where {[] a ?Concept} LIMIT 20
select distinct ?subject 
where {
   ## ?subject a rdf:Description .
   ## ?subject  ?p ?o .
   ?subject pica:f003Y ?o .
   ## ?subject a bibo:Article .
   ## ?subject dct:identifier ?o .
   ## ?subject dct:modified ?date .
   FILTER (!isBlank(?subject)) .
   ## FILTER (?date > "2013-01-01")
   ## FILTER (?date > "<date>")
}
## ORDER BY DESC(?subject)

