PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms: <http://purl.org/dc/terms/>

# check size of store
SELECT (COUNT(distinct(?s)) AS ?subject) 
WHERE { 
   ?s ?p ?o .
   ?s dcterms:identifier ?o .
   FILTER regex(?s,'^http://archiv.ub.uni-marburg.de')
}
