PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dct: <http://purl.org/dc/terms/>

# check size of store
SELECT (COUNT(distinct(?s)) AS ?subject) 
WHERE { 
   ?s ?p ?o .
   ?s dct:identifier ?o .
}
