#!/bin/sh

dir=`dirname $0`

CP=$dir/lib; for l in $dir/lib/*.jar; do
  CP=$CP:$l
done

hostname="`hostname`"
case $hostname in
  macbook*|pcub803)
    CP=dlib:$CP; for l in $dir/dlib/*.jar; do CP=$CP:$l ; done
    # java -cp $CP org.shanghai.nlp.Main $*
    java -cp $CP org.shanghai.main.Main -conf lib/archiv.ttl $*
    ;;
  *)
    java -cp $CP org.shanghai.main.Main $*
    ;;
esac

