
PREFIX  dc: <http://purl.org/dc/elements/1.1/>
PREFIX  dct: <http://purl.org/dc/terms/>

select distinct ?subject 
## FROM NAMED <http://archiv.ub.uni-marburg.de>
where 
{
   GRAPH <http://archiv.ub.uni-marburg.de> {
     ## ?subject  dc:identifier ?identifier .
     ?subject  ?p ?o
   }
}
   ORDER BY DESC(?subject)

