#
# DNB data 2013-02
#
PREFIX  dc: <http://purl.org/dc/elements/1.1/>
PREFIX  dcterms: <http://purl.org/dc/terms/>
PREFIX  gnd: <http://d-nb.info/standards/elementset/gnd#>
PREFIX  bibo: <http://purl.org/ontology/bibo/>
PREFIX  rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  ifla: <http://iflastandards.info/ns/isbd/elements/>
PREFIX  owl: <http://www.w3.org/2002/07/owl#>
PREFIX  foaf: <http://xmlns.com/foaf/spec/>

construct 
{
    %param% ?p1 ?o1 .
    ?o1 ?x ?y . 
}
where {
  {
     %param% ?p1 ?o1 .
     optional {
       ?o1 ?x ?y 
       FILTER (isBlank(?o1) && !isBlank(?y))
     }
     optional {
       ?o1 ?x ?y .
       %param% dcterms:creator ?o1
     }
  } 
}
