PREFIX  dcterms: <http://purl.org/dc/terms/>
PREFIX  dc: <http://purl.org/dc/elements/1.1/>
PREFIX  gnd: <http://d-nb.info/standards/elementset/gnd#>

construct 
{
    %param% ?p1 ?o1 .
    ?o1 ?x ?y . 
}
where {
  {
     %param% ?p1 ?o1 .
     optional {
       ?o1 ?x ?y 
       FILTER (isBlank(?o1) && !isBlank(?y))
     }
  } 
}
