
PREFIX  dcterms: <http://purl.org/dc/terms/>
PREFIX  dc: <http://purl.org/dc/elements/1.1/>
PREFIX  gnd: <http://d-nb.info/standards/elementset/gnd#>

 select ?s ?o  where 
 {
    # gnd:DifferentiatedPerson ?p ?o .
    # ?s gnd:gndIdentifier ?o .
    ?s gnd:gender ?o .
 }


