
PREFIX  dcterms: <http://purl.org/dc/terms/>
PREFIX  dc: <http://purl.org/dc/elements/1.1/>

select ?subject ?identifier  where 
{
   ?subject  dc:identifier ?identifier .
}
   ORDER BY DESC(?subject)

