PREFIX  dc: <http://purl.org/dc/elements/1.1/>
PREFIX  dcterms: <http://purl.org/dc/terms/>
PREFIX  dcmitype: <http://purl.org/dc/dcmitype/>
PREFIX  dcq: <http://purl.org/dc/qualifier/1.0/>

PREFIX  dnb: <http://www.d-nb.de/standards/ddb/>
PREFIX  gnd: <http://d-nb.info/gnd/>
PREFIX  xmdp: <http://www.d-nb.de/standards/xmetadissplus/type/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  ndltd: <http://www.ndltd.org/standards/metadata/etdms/1.0/>
PREFIX  fabio: <http://purl.org/spar/fabio/>

PREFIX  thesis: <http://www.ndltd.org/standards/metadata/etdms/1.0/>
PREFIX  urn: <http://www.d-nb.de/standards/urn/>
PREFIX  dini: <http://www.d-nb.de/standards/xmetadissplus/type/>
PREFIX  bibo: <http://purl.org/ontology/bibo/>

## resource dump.
construct 
{
    <subject> ?p ?o .
    ?o ?x ?y . 
} 
where {
    <subject> ?p ?o .
    optional {
       ?o ?x ?y 
       FILTER (isBlank(?o) && !isBlank(?y))
    }
    optional {
       <subject> dcterms:isPartOf ?o .
       ?o ?x ?y
    }
} 

