PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dc: <http://purl.org/dc/elements/1.1/>

# check size of store
SELECT (COUNT(distinct(?s)) AS ?subject) 
WHERE { 
     ?s ?p ?o .
     FILTER (!isBlank(?s))
}
