
PREFIX  dc: <http://purl.org/dc/elements/1.1/>
PREFIX  dct: <http://purl.org/dc/terms/>

select distinct ?subject 
where {
   ?subject  ?p ?o
   FILTER (!isBlank(?subject))
}
   ORDER BY DESC(?subject)

